POST http://localhost:8080/users/login
Accept: application/json
Content-Type: application/json

{ "username": "nesto", "password": "koko" }



# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
GET http://localhost:8080/restaurants
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXN0byIsImF1dGgiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTU3NDUxMDY3MiwiZXhwIjoxNTc0NTE0MjcyfQ.WpAhRspJsiVccMet9wG-TiUZf_CSMIMyXkHzscRH55U

###



